// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VitaLog.Api.Infrastructure.Database;

#nullable disable

namespace VitaLog.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423080322_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ServingSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("TimeOfDay")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Courses_UpdatedAt");

                    b.HasIndex("ProductId", "UpdatedAt")
                        .HasDatabaseName("IX_Courses_ProductId_UpdatedAt");

                    b.HasIndex("UserId", "UpdatedAt")
                        .HasDatabaseName("IX_Courses_UserId_UpdatedAt");

                    b.ToTable("Courses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Courses_EndDate_AfterOrEqual_StartDate", "\"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\"");

                            t.HasCheckConstraint("CK_Courses_ServingSize_Positive", "\"ServingSize\" > 0");
                        });
                });

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.GlobalIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_GlobalIngredients_Name_Active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_GlobalIngredients_UpdatedAt");

                    b.ToTable("GlobalIngredients", (string)null);
                });

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.IntakeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualServingSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("TakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_IntakeLogs_UpdatedAt");

                    b.HasIndex("CourseId", "TakenAt")
                        .HasDatabaseName("IX_IntakeLogs_CourseId_TakenAt_Active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("UserId", "TakenAt")
                        .HasDatabaseName("IX_IntakeLogs_UserId_TakenAt_Active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("UserId", "UpdatedAt")
                        .HasDatabaseName("IX_IntakeLogs_UserId_UpdatedAt");

                    b.ToTable("IntakeLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_IntakeLogs_ActualServingSize_Positive", "\"ActualServingSize\" > 0");
                        });
                });

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Products_Name_Active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Products_UpdatedAt");

                    b.HasIndex("CreatorUserId", "UpdatedAt")
                        .HasDatabaseName("IX_Products_CreatorUserId_UpdatedAt");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.ProductIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("CustomIngredientName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_ProductIngredients_UpdatedAt");

                    b.HasIndex("ProductId", "CustomIngredientName")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductIngredients_Product_CustomIngredient_Active")
                        .HasFilter("\"DeletedAt\" IS NULL AND \"IngredientId\" IS NULL AND \"CustomIngredientName\" IS NOT NULL");

                    b.HasIndex("ProductId", "IngredientId")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductIngredients_Product_Ingredient_Active")
                        .HasFilter("\"DeletedAt\" IS NULL AND \"IngredientId\" IS NOT NULL");

                    b.HasIndex("ProductId", "UpdatedAt")
                        .HasDatabaseName("IX_ProductIngredients_ProductId_UpdatedAt");

                    b.ToTable("ProductIngredients", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductIngredients_Amount_Positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_ProductIngredients_Hybrid_IngredientOrCustom", "(\r\n    (\"IngredientId\" IS NOT NULL AND \"CustomIngredientName\" IS NULL)\r\n    OR\r\n    (\"IngredientId\" IS NULL AND \"CustomIngredientName\" IS NOT NULL AND length(trim(\"CustomIngredientName\")) > 0)\r\n)");
                        });
                });

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Roles")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email_Active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Users_UpdatedAt");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("UX_UserRefreshTokens_Token");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_UserRefreshTokens_UpdatedAt");

                    b.HasIndex("UserId", "RevokedAt", "ExpiresAt")
                        .HasDatabaseName("IX_UserRefreshTokens_UserId_RevokedAt_ExpiresAt");

                    b.ToTable("UserRefreshTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserRefreshTokens_ExpiresAt_After_CreatedAt", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("CK_UserRefreshTokens_RevokedAt_After_CreatedAt", "\"RevokedAt\" IS NULL OR \"RevokedAt\" >= \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.Course", b =>
                {
                    b.HasOne("VitaLog.Api.Domain.Entities.Product", "Product")
                        .WithMany("Courses")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VitaLog.Api.Domain.Entities.User", "User")
                        .WithMany("Courses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.IntakeLog", b =>
                {
                    b.HasOne("VitaLog.Api.Domain.Entities.Course", "Course")
                        .WithMany("IntakeLogs")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VitaLog.Api.Domain.Entities.User", "User")
                        .WithMany("IntakeLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.Product", b =>
                {
                    b.HasOne("VitaLog.Api.Domain.Entities.User", "CreatorUser")
                        .WithMany("CreatedProducts")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatorUser");
                });

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.ProductIngredient", b =>
                {
                    b.HasOne("VitaLog.Api.Domain.Entities.GlobalIngredient", "Ingredient")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VitaLog.Api.Domain.Entities.Product", "Product")
                        .WithMany("Ingredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.UserRefreshToken", b =>
                {
                    b.HasOne("VitaLog.Api.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.Course", b =>
                {
                    b.Navigation("IntakeLogs");
                });

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.GlobalIngredient", b =>
                {
                    b.Navigation("ProductIngredients");
                });

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.Product", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("VitaLog.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("CreatedProducts");

                    b.Navigation("IntakeLogs");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
